OnlineHotelReservationSystem/Controllers/AjaxController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace OnlineHotelReservationSystem.Controllers
{
    public class AjaxController : Controller
    {
        // GET: Ajax
        public ActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public JsonResult SuiteList(Suite model)
        {

            var db = new HotelDatabase();
            var addSuite = new Suite();
            addSuite.SuiteType = model.SuiteType;
            addSuite.SuitePrice = model.SuitePrice;
            addSuite.TotalNumber = model.TotalNumber;

            db.Suites.Add(addSuite);
            db.SaveChanges();

            var suiteData = new Suite();
            var lst = db.Suites.AsQueryable();

            var res = new JsonResult();

            var SuiteData = db.Suites.AsQueryable().OrderByDescending(o => o.SuiteType).ToList();

            res.Data = SuiteData;

            res.JsonRequestBehavior = JsonRequestBehavior.AllowGet;//允许使用GET方式获取，否则用GET获取是会报错。  
            return Json(GetResult(false, "添加成功", res));

        }

        public static object GetResult(bool rel, string msg, object data)
        {
            return new Dictionary<string, object> { { "rel", rel }, { "msg", msg }, { "obj", data } };

        }
       
    }
}

OnlineHotelReservationSystem/Controllers/BackstageManageController.cs
using Microsoft.AspNet.Identity;
using OnlineHotelReservationSystem.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace OnlineHotelReservationSystem.Controllers
{
    public class BackstageManageController : Controller
    {
        // GET: BackstageManage
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult LoginSysAdmin()
        {
            return View();
        }

        public ActionResult LoginSysAdminState()
        {
            return View();
        }

        /// <summary>
        /// 单个用户，查看自己的所有订单
        /// </summary>
        /// <returns></returns>
        public ActionResult SingleOrderList()
        {
            var db = new HotelDatabase();
            var nowUser = User.Identity.GetUserName();
            var singleList = db.ReserveInfos.AsQueryable().Where(o => o.UserName.Equals(nowUser));
            ViewBag.SingleUserOrderList = singleList.OrderBy(o => o.OrderId).ToList();
            return View();
        }
        /// <summary>
        /// 用户退订，删除订单
        /// </summary>
        /// <returns></returns>
        public ActionResult SingleOrderListDelete(int OrderId)
        {
            var db = new HotelDatabase();
            var singleDel = db.ReserveInfos.First(o => o.OrderId == OrderId);
            db.ReserveInfos.Remove(singleDel);
            db.SaveChanges();
            return RedirectToAction("SingleOrderList");
        }

        /// <summary>
        /// 登录验证
        /// </summary>
        /// <param name="model">接收数据</param>
        /// <returns></returns>
        public ActionResult LoginSysAdminSave(SysAdmin model)
        {
            var state = false;
            var db = new HotelDatabase();
            if (ModelState.IsValid)
            {
                db.Database.CreateIfNotExists();

                var lst = db.SysAdmins.AsQueryable();
                lst = lst.Where(o => o.SysAdminName.Contains(model.SysAdminName));
                foreach (var q in lst)
                {
                    if (q.SysAdminName == model.SysAdminName && q.SysAdminPassword == model.SysAdminPassword)
                    {
                        state = true;
                    }
                    else state = false;
                }
            }
            if (state == true)
            {
                try
                {
                    var stateLogin = new SysAdminLogin();
                    stateLogin.SysAdminLoginState = "true";
                    stateLogin.SysAdminName = model.SysAdminName;
                    ViewBag.SysAdminName = model.SysAdminName;
                    db.SysAdminLogins.Add(stateLogin);
                    db.SaveChanges();

                    return RedirectToAction("OrderListIndex", "BackstageManage");
                }
                catch (ArgumentNullException e)
                {
                    return Content("<script> alert('该账号已登录！'); </script>");
                }

            }
            else return View("LoginSysAdmin");
        }
        /// <summary>
        /// 管理员退出登录
        /// </summary>
        /// <param name="name"></param>
        /// <returns></returns>
        public ActionResult LoginSysAdminExit(string name)
        {
            var db = new HotelDatabase();
            var state = db.SysAdminLogins.First(o => o.SysAdminName == name);
            db.SysAdminLogins.Remove(state);
            db.SaveChanges();
            return RedirectToAction("LoginSysAdmin", "BackstageManage");
        }
        public ActionResult RegisterSysAdmin()
        {
            return View();
        }

        /// <summary>
        /// 注册信息保存
        /// </summary>
        /// <param name="model">接收数据</param>
        /// <returns></returns>
        public ActionResult RegisterSysAdminSave(SysAdmin model)
        {
            if (ModelState.IsValid)
            {
                var db = new HotelDatabase();
                db.Database.CreateIfNotExists();

                var sysAdmin = new SysAdmin();
                sysAdmin.SysAdminName = model.SysAdminName;
                sysAdmin.SysAdminPassword = model.SysAdminPassword;
                sysAdmin.SysAdminIdCode = model.SysAdminIdCode;
                db.SysAdmins.Add(sysAdmin);
                db.SaveChanges();
            }
            return View("LoginSysAdmin");
        }
        /// <summary>
        /// 管理员删除订单
        /// </summary>
        /// <param name="OrderId"></param>
        /// <returns></returns>
        public ActionResult OrderListDelete(int OrderId)
        {
            var db = new HotelDatabase();
            var singleDel = db.ReserveInfos.First(o => o.OrderId == OrderId);
            db.ReserveInfos.Remove(singleDel);
            db.SaveChanges();
            return RedirectToAction("OrderListIndex");
        }

        /// <summary>
        /// 保存预定信息
        /// </summary>
        /// <returns></returns>
        public ActionResult OrderSave(ReserveInfo model)
        {
            var flag = false;
            if (HttpContext.User.Identity.IsAuthenticated == true) //已登录
            {
                var db = new HotelDatabase();
                db.Database.CreateIfNotExists();
                var saveInfo = new ReserveInfo();

                var lst = db.Suites.AsQueryable().Where(o => o.SuiteType.Contains(model.SuiteType)); ///查询价格
                var price = 100;
                foreach (var q in lst)
                {
                    if (true)
                    {
                        price = q.SuitePrice;
                        break;
                    }
                }
                //var d1 = model.ArrivalTime;
                //var d2 = model.ArrivalTime;
                //var dtArrival = d1.ToString("yyyy/MM/dd");
                //var dtLevel = d2.ToString("yyyy/MM/dd");
                saveInfo.UserName = User.Identity.GetUserName(); //当前登录用户
                saveInfo.OrderName = model.OrderName;
                saveInfo.OrderIdCard = model.OrderIdCard;
                saveInfo.OrderTime = DateTime.Now;
                saveInfo.SuiteType = model.SuiteType;
                saveInfo.OrderNunber = model.OrderNunber;
                saveInfo.ArrivalTime = model.ArrivalTime;
                saveInfo.LeaveTime = model.LeaveTime;
                saveInfo.Tel = model.Tel;
                saveInfo.TotalPrice = price * model.OrderNunber;

                db.ReserveInfos.Add(saveInfo);
                db.SaveChanges();
                flag = true;
            }
            if (flag == true)
            {
                //return Content("<script> alert('预订成功'); </script>");
                return View();
            }
            else
                return RedirectToAction("Login", "Account");
        }

        /// <summary>
        /// 订单管理页面
        /// </summary>
        /// <returns></returns>
        public ActionResult OrderListIndex()
        {
            var db = new HotelDatabase();

            var reserveInfoData = new ReserveInfo();
            var lst = db.ReserveInfos.AsQueryable();

            ViewBag.ReserveInfoData = lst.OrderByDescending(o => o.OrderId).ToList();
            ViewData["sysname"] = GetSysAdminName();
            return View();
        }


        /// <summary>
        /// 订单修改页面处理
        /// </summary>
        /// <param name="OrderId"></param>
        /// <returns></returns>
        public ActionResult OrderListEdit(int OrderId)
        {
            var db = new HotelDatabase();
            var changeList = db.ReserveInfos.First(o => o.OrderId == OrderId);

            ViewData.Model = changeList;
            ViewData["sysname"] = GetSysAdminName();
            return View();
        }
        /// <summary>
        /// 订单修改保存
        /// </summary>
        /// <param name="changeSaveModel"></param>
        /// <returns></returns>
        public ActionResult OrderListEditSave(ReserveInfo changeSaveModel)
        {
            var db = new HotelDatabase();
            var changeSave = db.ReserveInfos.First(o => o.OrderId == changeSaveModel.OrderId);
            
            changeSave.OrderName = changeSaveModel.OrderName;
            changeSave.OrderIdCard = changeSaveModel.OrderIdCard;
            changeSave.Tel = changeSaveModel.Tel;
            
            db.SaveChanges();

            return RedirectToAction("OrderListIndex");
        }
        public ActionResult UserIndex()
        {
            var db = new HotelDatabase();
            var costomerData = new Customer();
            var lst = db.Customers.AsQueryable();
            ViewBag.CustomerData = lst.OrderByDescending(o => o.CustomerId).ToList();
            ViewData["sysname"] = GetSysAdminName();
            return View();
        }
        /// <summary>
        /// 房型管理
        /// </summary>
        /// <returns></returns>
        public ActionResult SuiteIndex()
        {
            var db = new HotelDatabase();

            var suiteData = new Suite();
            var lst = db.Suites.AsQueryable();

            ViewBag.SuiteData = lst.OrderByDescending(o => o.SuiteType).ToList();
            ViewData["sysname"] = GetSysAdminName();
            return View();
        }


        /// <summary>
        /// 增加房型 in SuiteIndex
        /// </summary>
        /// <param name="model"></param>
        /// <returns></returns>
        public ActionResult AddSuite(Suite model)
        {
            var db = new HotelDatabase();
            var addSuite = new Suite();

            addSuite.SuiteType = model.SuiteType;
            addSuite.SuitePrice = model.SuitePrice;
            addSuite.TotalNumber = model.TotalNumber;
            addSuite.OddNumber = addSuite.TotalNumber; //剩余数量等于总数量

            db.Suites.Add(addSuite);
            db.SaveChanges();

            return RedirectToAction("SuiteIndex");
        }

        /// <summary>
        /// 删除房型
        /// </summary>

OnlineHotelReservationSystem/Views/BackstageManage/12Index.cshtml
@{
    Layout = null;
    var suitedata = ViewBag.SuiteData as List<Suite>;
}
@model Suite

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>主页 - 后台管理系统</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

    <link rel="stylesheet" href="http://cdn.static.runoob.com/libs/bootstrap/3.3.7/css/bootstrap.min.css">
    <script src="http://cdn.static.runoob.com/libs/jquery/2.1.1/jquery.min.js"></script>
    <script src="http://cdn.static.runoob.com/libs/bootstrap/3.3.7/js/bootstrap.min.js"></script>

</head>





<body>
    <div class="container">

        <h2 class="h2 text-center">KEMPINSKI后台管理系统</h2>
        <br />
        管理员： 你好！
        <br /><br />
        <ul id="myTab" class="nav nav-tabs">

            <li>
                @Html.ActionLink("退出系统", "LoginSysAdmin", "BackstageManage")
            </li>
            <li>
                <a href="#orderList" data-toggle="tab">订单管理</a>
            </li>
            <li>
                <a href="#user" data-toggle="tab">用户管理</a>
            </li>
            <li>
                <a href="#add" data-toggle="tab">添加房型</a>
            </li>
        </ul>
        <div id="myTabContent" class="tab-content">

            <div class="tab-pane fade in active" id="orderList">
                <br /><br />
                <div id="orderListDiv">
                    @Html.Partial("_orderListTableView");
                </div>
                <br /><br />
                @using (Html.BeginForm("","",new { }))
                {

                }
             </div>
            <div class="tab-pane fade" id="user">
                <br /><br />
                <div id="orderListDiv">
                    @Html.Partial("_userTableView");
                </div>
                <br /><br />
                @using (Html.BeginForm("", "", new { }))
                {

                }
            </div>

        <div class="tab-pane fade" id="add">

            <br /><br />
            <div id="suiteDiv">
                @Html.Partial("_suiteTableView")
            </div>


            <br /><br />

            @using (Ajax.BeginForm("AddSuite", "BackstageManage", new AjaxOptions() { HttpMethod = "Post", UpdateTargetId = "suiteDiv", InsertionMode = InsertionMode.Replace }))
            {

                <div class="form-group">
                    <label for="SuiteType" class="col-sm-2 control-label">房间类型</label>
                    <div class="col-sm-10">
                        @Html.TextBoxFor(o => o.SuiteType, new { @class = "form-control", id = "SuiteType" })
                    </div>
                </div>
                    <br /><br /><br />
                    <div class="form-group">
                        <label for="SuitePrice" class="col-sm-2 control-label">房间价格</label>
                        <div class="col-sm-10">
                            @Html.TextBoxFor(o => o.SuitePrice, new { @class = "form-control", id = "SuitePrice" })
                        </div>
                    </div>
                    <br /><br />
                    <div class="form-group">
                        <label for="TotalNumber" class="col-sm-2 control-label">房间总数</label>
                        <div class="col-sm-10">
                            @Html.TextBoxFor(o => o.TotalNumber, new { @class = "form-control", id = "TotalNumber" })
                        </div>
                    </div>
                    <br /><br />
                    <div class="form-group">
                        <div class="col-sm-5"></div>
                        <div class="col-sm-5">
                            <input type="submit" class="btn btn-default" value="保存" onclick="javascript:upclick(this);" />
                        </div>
                    </div>
            }
        </div>
    </div>

    </div>

    <script>
        $(function () {
            $('#myTab li:eq(1) a').tab('show');
        });
    </script>

</body>
</html>

OnlineHotelReservationSystem/Views/BackstageManage/LoginSysAdmin.cshtml
@{
    Layout = null;
}
@model SysAdmin
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>注册KEMPINSKI后台管理账户</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a href="@Url.Action("Index","Home")"><img src="~/Content/images/corp-logo.png" height="50" /></a>
                @*@Html.ActionLink("Index", "Home", new { area = "" }, new { @class = "navbar-brand" })*@
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("主页", "Index", "Home")</li>
                    <li>@Html.ActionLink("目的地", "About", "Home")</li>
                    <li>@Html.ActionLink("预定房间", "Index", "Home")</li>
                    <li>@Html.ActionLink("最新优惠", "About", "Home")</li>
                    <li>@Html.ActionLink("关于凯宾斯基", "Contact", "Home")</li>
                    <li>@Html.ActionLink("凯宾斯基博客", "Contact", "Home")</li>
                </ul>

            </div>
        </div>
    </div>
    <br /><br /><br /><br /><br /><br />
    <div class="container">
        @using (Html.BeginForm("LoginSysAdminSave", "BackstageManage"))
        {
            @*@Html.AntiForgeryToken()*@
            <h4>登录到KEMPINSKI后台</h4>
            <hr />
            <br />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <div class="form-group">
                <span class="col-md-2 control-label">登录名</span>
                <div class="col-md-10">
                    @Html.TextBoxFor(m => m.SysAdminName, new { @class = "form-control" })
                </div>
            </div>
            <br /><br />
            <div class="form-group">
                <span class="col-md-2 control-label">密码</span>
                <div class="col-md-10">
                    @Html.PasswordFor(m => m.SysAdminPassword, new { @class = "form-control" })
                </div>
            </div>
            <br /><br />
            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="登录" class="btn btn-default" /> &nbsp;&nbsp;&nbsp;
                    @Html.ActionLink("注册为管理员", "RegisterSysAdmin", "BackstageManage")
                </div>
            </div>
        }

    </div>

    <div class="container body-content">
        <hr />
        <br />
        <footer class="text-center" style="position: relative;margin-top: -30px; height: 30px;clear:both; ">
            <p>&copy; @DateTime.Now.Year - 我的 ASP.NET 应用程序</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")

</body>
</html>

OnlineHotelReservationSystem/Views/BackstageManage/OrderListEdit.cshtml
@{
    Layout = null;
}
@model ReserveInfo
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>修改订单 - 后台管理系统</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="container">

        <h2 class="h2 text-center">KEMPINSKI后台管理系统</h2>
        <br />
        <p>管理员：<label class="text-danger"> @ViewData["sysname"] </label> , 你好！</p>
        <br /><br />
        <ul id="myTab" class="nav nav-tabs">

            <li>
                @Html.ActionLink("退出系统", "LoginSysAdminExit", "BackstageManage", new { name = @ViewData["sysname"] })
            </li>
            <li>
                @Html.ActionLink("订单管理", "OrderListIndex", "BackstageManage", new { })
            </li>
            <li>
                @Html.ActionLink("用户管理", "UserIndex", "BackstageManage", new { })
            </li>
            <li>
                @Html.ActionLink("房型管理", "SuiteIndex", "BackstageManage", new { })
            </li>
        </ul>
        <br /> <br />

        @using (Html.BeginForm("OrderListEditSave", "BackstageManage", new { @class = "form-horizontal" }))
        {
            <input type="hidden" value="@Model.OrderId" name="OrderId" />
            <input type="hidden" value="@Model.UserName" name="UserName" />
            <div class="form-group">
                <span class="col-md-2 control-label">房间类型</span>
                <div class="col-md-10">
                    <label>@Model.SuiteType</label>
                </div>
            </div>
            <br /><br />
            <div class="form-group">
                <span class="col-md-2 control-label">预定数量</span>
                <div class="col-md-10">
                    <label>@Model.OrderNunber</label>
                </div>
            </div>
            <br /><br />
            <div class="form-group">
                <span class="col-md-2 control-label">预定时间</span>
                <div class="col-md-10">
                    <label>@Model.OrderTime</label>
                </div>
            </div>
            <br /><br />
            <div class="form-group">
                <span class="col-md-2 control-label">预订人</span>
                <div class="col-md-10">
                    @Html.TextBoxFor(m => m.OrderName, new { @class = "form-control" })
                </div>
            </div>
            <br /><br />
            <div class="form-group">
                <span class="col-md-2 control-label">身份证号</span>
                <div class="col-md-10">
                    @Html.TextBoxFor(m => m.OrderIdCard, new { @class = "form-control" })
                </div>
            </div>
            <br /><br />
            <div class="form-group">
                <span class="col-md-2 control-label">联系电话</span>
                <div class="col-md-10">
                    @Html.TextBoxFor(m => m.Tel, new { @class = "form-control" })
                </div>
            </div>
            <br /><br />
            <div class="form-group">
                <span class="col-md-2 control-label">入住时间</span>
                <div class="col-md-10">
                    <label class="control-label">@Model.ArrivalTime</label>
                </div>
            </div>
            <br /><br />
            <div class="form-group">
                <span class="col-md-2 control-label">退房时间</span>
                <div class="col-md-10">
                    <label class="control-label">@Model.LeaveTime</label>
                </div>
            </div>
            <br /><br />
            <div class="form-group">
                <span class="col-md-2 control-label">总价</span>
                <div class="col-md-10">
                    <label class="text-danger">@Model.TotalPrice 元</label>
                </div>
            </div>
            <br /><br />
            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="确认并保存" class="btn btn-danger" /> 
                </div>
            </div>

        }
    </div>
</body>
</html>

OnlineHotelReservationSystem/Views/BackstageManage/OrderListIndex.cshtml
@{
    Layout = null;
    var reserveInfoData = ViewBag.ReserveInfoData as List<ReserveInfo>;
}
@model ReserveInfo

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>订单管理 - 后台管理系统</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>

<body>
    <div class="container">

        <h2 class="h2 text-center">KEMPINSKI后台管理系统</h2>
        <br />
        <p>管理员：<label class="text-danger"> @ViewData["sysname"] </label> , 你好！</p>
        <br />
        <ul id="myTab" class="nav nav-tabs">
            <li>
                @Html.ActionLink("退出系统", "LoginSysAdmin", "BackstageManage", new { name = @ViewData["sysname"] })
            </li>
            <li>
                @Html.ActionLink("订单管理", "OrderListIndex", "BackstageManage", new { })
            </li>
            <li>
                 @Html.ActionLink("用户管理", "UserIndex", "BackstageManage", new { })
            </li>
            <li>
                 @Html.ActionLink("房型管理", "SuiteIndex", "BackstageManage", new { })
            </li>
        </ul>
        <div id="myTabContent" class="tab-content" style="width:1300px; max-width:1500px">

            <div class="tab-pane fade in active" id="orderList">
                <br /><br />
                <div id="orderListDiv">
                    <table class="table table-hover">
                        <caption>订单列表</caption>
                        <thead>
                            <tr>
                                <th>订单号</th>
                                <th>预定账户</th>
                                <th>预定时间</th>
                                <th>房间类型</th>
                                <th>预定数量</th>
                                <th>总价</th>
                                <th>预订人</th>
                                <th>身份证号</th>
                                <th>联系电话</th>
                                <th>入住时间</th>
                                <th>退房时间</th>
                                <th>操作</th>
                            </tr>
                        </thead>
                        <tbody>
                            @if (reserveInfoData != null)
                            {
                                foreach (var item in reserveInfoData)
                                {
                                    <tr>
                                        <td> @item.OrderId</td>
                                        <td> @item.UserName</td>
                                        <td> @item.OrderTime</td>
                                        <td> @item.SuiteType</td>
                                        <td> @item.OrderNunber 间</td>
                                        <td> @item.TotalPrice</td>
                                        <td> @item.OrderName</td>
                                        <td> @item.OrderIdCard</td>
                                        <td> @item.Tel   </td>
                                        <td> @item.ArrivalTime</td>
                                        <td> @item.LeaveTime</td>
                                        <td>
                                            @Html.ActionLink("[  修改  ]", "OrderListEdit", new { OrderId = item.OrderId }) |
                                            @Html.ActionLink("[  删除  ]", "OrderListDelete", new { OrderId = item.OrderId })
                                        </td>
                                    </tr>
                                }
                            }
                            else
                            {
                                <tr>
                                    <td>没有数据</td>
                                    <td>没有数据</td>
                                    <td>没有数据</td>
                                    <td>没有数据</td>
                                    <td>无法执行</td>
                                </tr>
                            }
                        </tbody>
                    </table>
                </div>
                <br /><br />

            </div>
            <div class="tab-pane fade" id="user">

            </div>

            <div class="tab-pane fade" id="add">


            </div>
        </div>

    </div>

</body>
</html>
    >

OnlineHotelReservationSystem/Views/BackstageManage/OrderSave.cshtml
@{
    ViewBag.Title = "OrderSave";
}


<div class="container">

    <h3>预订成功</h3>
    <br /><br />
    @Html.ActionLink("立即查看我的订单","SingleOrderList","BackstageManage");
</div>

OnlineHotelReservationSystem/Views/BackstageManage/SingleOrderList.cshtml
@{
    ViewBag.Title = "SingleOrderList";
    var singleList = ViewBag.SingleUserOrderList as List<ReserveInfo>;
}



<div class="container">
    <h2>查看我的订单</h2>

    <table class="table table-hover">
        <caption>所有订单</caption>
        <thead>
            <tr>
                <th>订单号</th>
                <th>房间类型</th>
                <th>预定数量</th>
                <th>预订人</th>
                <th>身份证号</th>
                <th>联系电话</th>
                <th>入住时间</th>
                <th>退房时间</th>
                <th>总价</th>
                <th>操作</th>
            </tr>
        </thead>
        <tbody>
            @if (singleList != null)
            {
                foreach (var item in singleList)
                {
                    <tr>
                        <td> @item.OrderId</td>
                        <td> @item.SuiteType</td>
                        <td> @item.OrderNunber 间</td>
                        <td> @item.OrderName</td>
                        <td> @item.OrderIdCard</td>
                        <td> @item.Tel</td>
                        <td> @item.ArrivalTime</td>
                        <td> @item.LeaveTime</td>
                        <td class="text-danger"> @item.TotalPrice 元</td>
                        <td>
                             @Html.ActionLink("[  退订  ]", "SingleOrderListDelete", new { OrderId = item.OrderId })
                        </td>
                    </tr>
                }
            }
            else
            {
                <tr>
                    <td>没有数据</td>
                    <td>没有数据</td>
                    <td>没有数据</td>
                    <td>没有数据</td>
                    <td>没有数据</td>
                    <td>没有数据</td>
                    <td>没有数据</td>
                    <td>没有数据</td>
                    <td>无法执行</td>
                </tr>
            }
        </tbody>
    </table>





</div>

OnlineHotelReservationSystem/Views/BackstageManage/_suiteTableView.cshtml
@{
    Layout = null;
    var suitedata = ViewBag.SuiteData as List<Suite>;
}

<table class="table table-hover">
    <caption>已存在的房型信息</caption>
    <thead>
        <tr>
            <th>编号</th>
            <th>房间类型</th>
            <th>房间价格</th>
            <th>房间总数</th>
            <th>操作</th>
        </tr>
    </thead>
    <tbody>
        @if (suitedata != null)
        {
            foreach (var item in suitedata)
            {
                <tr>
                    <td> @item.SuiteId</td>
                    <td> @item.SuiteType</td>
                    <td> @item.SuitePrice</td>
                    <td> @item.TotalNumber</td>
                    <td>
                        @Html.ActionLink("[  编辑  ]", "", new { SuiteId = item.SuiteId }) |
                        @Html.ActionLink("[  删除  ]", "SuiteDelete", new { SuiteId = item.SuiteId })
                    </td>
                </tr>
            }
        }
        else
        {
            <tr>
                <td>没有数据</td>
                <td>没有数据</td>
                <td>没有数据</td>
                <td>没有数据</td>
                <td>无法执行</td>
            </tr>
        }
    </tbody>
</table>

    <script type="text/javascript">
        function upclick(o) {
            var SuiteType = $("#SuiteType").val();
            var SuitePrice = $("#SuitePrice").val();
            var TotalNumber = $("#TotalNumber").val();
            alert(obj);
            $.ajax({
                url: @Html.ActionLink("SuiteList","Ajax"),
                type: "GET",
                dataType: "json",
                data: { "SuiteType":SuiteType,"SuitePrice":SuitePrice,"TotalNumber":TotalNumber},
                success: function (data) {

                    alert(data);
                }
            })
        }
    </script>

OnlineHotelReservationSystem/Views/BackstageManage/_userTableView.cshtml
<table class="table table-hover">
    <caption>用户列表</caption>
    <thead>
        <tr>
            <th>用户名</th>
            <th>会员等级</th>
            <th>操作</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td>Tanmay</td>
            <td>Bangalore</td>
            <td></td>
        </tr>

    </tbody>
</table>